Resources:

  Textures:
    - id: "t1"
      name: "main_texture"
      path: "Domain/assets/textures/main_texture.png"
      filtering: "linear"
      wrap: "clamp"

    - id: "t2"
      name: "mushroom_texture"
      path: "Domain/assets/textures/mushroom_texture.png" 
      filtering: "linear"
      wrap: "repeat"
 
  Shaders:
    - id: "s1"
      vert_path: "Domain/assets/shaders/sprite.vert"
      frag_path: "Domain/assets/shaders/sprite.frag"
      name: "sprite"

    - id: "s2"
      vert_path: "Domain/assets/shaders/grid.vert"
      frag_path: "Domain/assets/shaders/grid.frag"
      name: "grid"

    - id: "s3"
      vert_path: "Domain/assets/shaders/sprite.vert"
      frag_path: "Domain/assets/shaders/glow.frag"
      name: "glow"

  Materials:
    - id: "m1"
      name: "default"
      shader_id: "s1"
      uniforms: {
        textures: { uTexture: "t2"},
        floats: { },
        vec2: { uUVScale : [1.0, 1.0], uUVOffset: [0.0, 0.0] },
        vec4: { uColor : [1.0, 1.0, 1.0, 1.0]}
      }

  Sprites:
    - id: "sprite1"
      name: "mushroom_frame_1"
      texture_id: "t2"
      uvMin: [0.0, 0.0]       
      uvMax: [1.0, 1.0]       
      pivot: [0, 0]        
