Resources:

  Textures:
    - id: "t1"
      name: "main_texture"
      path: "Domain/assets/textures/smiley_texture.png"
      filtering: "linear"
      wrap: "clamp"

    - id: "t2"
      name: "smiley_texture"
      path: "Domain/assets/textures/smiley_texture.png" 
      filtering: "linear"
      wrap: "repeat"

    - id: "t3"
      name: "smiley_texture"
      path: "Domain/assets/textures/smiley_texture.png" 
      filtering: "linear"
      wrap: "repeat"
 
  Shaders:
    - id: "s1"
      vert_path: "Domain/assets/shaders/sprite.vert"
      frag_path: "Domain/assets/shaders/sprite.frag"
      name: "sprite"

    - id: "s2"
      vert_path: "Domain/assets/shaders/grid.vert"
      frag_path: "Domain/assets/shaders/grid.frag"
      name: "grid"

  Materials:
    - id: "m1"
      name: "default"
      shader_id: "s1"
      texture_id: "t1"
